name: Windows EXE and Installer

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Install build tools (Inno Setup, Tesseract, Poppler)
        run: |
          choco install -y innosetup
          choco install -y tesseract
          rem Try poppler; fall back to poppler-tools if needed
          choco install -y poppler || choco install -y poppler-tools
        shell: cmd

      - name: Build app with PyInstaller (onedir)
        run: |
          pyinstaller --windowed --noconsole ^
            --name "AanAI" ^
            --icon assets\app.ico ^
            --add-data "assets\fonts;assets\fonts" ^
            --add-data "logo.png;." ^
            app.py
        shell: cmd

      - name: Show dist tree
        run: |
          if (Test-Path dist) {
            Get-ChildItem -Recurse -File dist | Select-Object FullName, Length | Format-Table -AutoSize
          } else {
            Write-Host "dist/ not found (PyInstaller may have failed)."
          }
        shell: pwsh

      - name: Prepare vendor binaries (Tesseract & Poppler)
        run: |
          $ErrorActionPreference = 'Stop'
          $dist = "dist/AanAI"
          New-Item -ItemType Directory -Force -Path "$dist/vendor/tesseract" | Out-Null
          New-Item -ItemType Directory -Force -Path "$dist/vendor/poppler/bin" | Out-Null
          
          # Tesseract (exe and tessdata)
          $tessRoot = "C:/Program Files/Tesseract-OCR"
          if (-not (Test-Path "$tessRoot/tesseract.exe")) {
            Write-Error "Tesseract not found at $tessRoot"
          }
          # Copy core exe and all dependent DLLs
          Copy-Item "$tessRoot/tesseract.exe" "$dist/vendor/tesseract/" -Force
          Get-ChildItem "$tessRoot" -Filter *.dll | ForEach-Object { Copy-Item $_.FullName "$dist/vendor/tesseract/" -Force }
          if (Test-Path "$tessRoot/tessdata") {
            Copy-Item "$tessRoot/tessdata" "$dist/vendor/tesseract/" -Recurse -Force
          }
          
          # Poppler bins (Chocolatey installs under lib/poppler*/tools)
          $popplerTools = $null
          $popplerPkg = Get-ChildItem "C:/ProgramData/chocolatey/lib" -Filter "poppler*" -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if ($popplerPkg) {
            $candidate = Join-Path $popplerPkg.FullName "tools"
            if (Test-Path $candidate) { $popplerTools = $candidate }
          }
          if (-not $popplerTools) {
            $fallback = "C:/Program Files/poppler/bin"
            if (Test-Path $fallback) { $popplerTools = $fallback }
          }
          if ($popplerTools) {
            Copy-Item "$popplerTools/*" "$dist/vendor/poppler/bin/" -Recurse -Force
          } else {
            Write-Warning "Poppler tools not found; PDF conversion may fail"
          }
        shell: pwsh

      - name: Ensure tessdata languages (eng, khm)
        run: |
          $tessdata = "dist/AanAI/vendor/tesseract/tessdata"
          New-Item -ItemType Directory -Force -Path $tessdata | Out-Null
          $langs = @("eng","khm")
          foreach ($l in $langs) {
            $dest = Join-Path $tessdata "$l.traineddata"
            if (-not (Test-Path $dest)) {
              Write-Host "Downloading $l.traineddata..."
              $url = "https://github.com/tesseract-ocr/tessdata/raw/main/$l.traineddata"
              try {
                Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing
              } catch {
                Write-Warning "Failed to download $l from tessdata main; trying tessdata_best"
                $url2 = "https://github.com/tesseract-ocr/tessdata_best/raw/main/$l.traineddata"
                Invoke-WebRequest -Uri $url2 -OutFile $dest -UseBasicParsing
              }
            }
          }
        shell: pwsh

      - name: Verify build outputs
        run: |
          if (-not (Test-Path "dist/AanAI/AanAI.exe")) { Write-Error "PyInstaller output not found" }
          if (-not (Test-Path "dist/AanAI/vendor/tesseract/tesseract.exe")) { Write-Error "Bundled Tesseract missing" }
          if (-not (Test-Path "dist/AanAI/vendor/poppler/bin")) { Write-Warning "Bundled Poppler missing" }
        shell: pwsh

      - name: Create installer with Inno Setup
        run: |
          $issc = 'C:/Program Files (x86)/Inno Setup 6/ISCC.exe'
          if (Test-Path $issc) {
            & $issc installer\aanai.iss
          } elseif (Get-Command iscc -ErrorAction SilentlyContinue) {
            iscc installer\aanai.iss
          } else {
            Write-Error 'Inno Setup (ISCC.exe) not found in default path or PATH.'
          }
        shell: pwsh

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: AanAI-Installer
          path: installer/dist/*.exe

      - name: Upload portable build (zip)
        run: |
          Compress-Archive -Path dist/AanAI/* -DestinationPath dist/AanAI-portable.zip
        shell: powershell
      - uses: actions/upload-artifact@v4
        with:
          name: AanAI-Portable
          path: dist/AanAI-portable.zip
